name: CassadyDesigns
favicon: null
layout_spectrum: 0.11855660658329725
typography_spectrum: 0.42914391797967255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.39406863134354353
  lightness: 0.9879082257393748
  saturation: 0.9414377247449011
  rhythmicContrast: 0.3766988564748317
purpose: []
